#!/bin/bash
# SocksClash v1.2.0 Configuration Generator
# 支持从订阅合并节点、生成代理组、规则等

CONFIG_DIR="/etc/socks-clash/config"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
UCI_CONFIG="socks-clash"
LOG_FILE="/tmp/socks-clash.log"

LOG_INFO() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [信息] $1" >> "$LOG_FILE"
}

# Load UCI settings
load_config() {
    enable=$(uci -q get $UCI_CONFIG.config.enable)
    socks_port=$(uci -q get $UCI_CONFIG.config.socks_port || echo "7891")
    http_port=$(uci -q get $UCI_CONFIG.config.http_port || echo "7890")
    mixed_port=$(uci -q get $UCI_CONFIG.config.mixed_port || echo "7893")
    cn_port=$(uci -q get $UCI_CONFIG.config.cn_port || echo "9090")
    log_level=$(uci -q get $UCI_CONFIG.config.log_level || echo "info")
    mode=$(uci -q get $UCI_CONFIG.config.mode || echo "rule")
    allow_lan=$(uci -q get $UCI_CONFIG.config.allow_lan || echo "1")
    bind_address=$(uci -q get $UCI_CONFIG.config.bind_address || echo "*")
    ipv6=$(uci -q get $UCI_CONFIG.config.ipv6 || echo "0")
    dashboard_password=$(uci -q get $UCI_CONFIG.config.dashboard_password || echo "")
    socks_enabled=$(uci -q get $UCI_CONFIG.config.socks_enabled || echo "1")
    http_enabled=$(uci -q get $UCI_CONFIG.config.http_enabled || echo "1")
    mixed_enabled=$(uci -q get $UCI_CONFIG.config.mixed_enabled || echo "0")
}

# Merge proxies from all subscription files
merge_proxies() {
    local temp_proxies="/tmp/merged_proxies_$$.yaml"
    
    LOG_INFO "正在合并订阅节点..."
    
    # 从所有订阅文件中提取 proxies 部分
    for sub_file in "$CONFIG_DIR"/*.yaml; do
        if [ -f "$sub_file" ] && [ "$sub_file" != "$CONFIG_FILE" ]; then
            LOG_INFO "处理订阅文件: $(basename $sub_file)"
            # 提取 proxies 部分（简化版，实际应该用YAML解析器）
            awk '/^proxies:/,/^[a-z-]+:/ {
                if (/^proxies:/) {
                    next
                }
                if (/^[a-z-]+:/) {
                    exit
                }
                print
            }' "$sub_file" >> "$temp_proxies"
        fi
    done
    
    if [ ! -s "$temp_proxies" ]; then
        LOG_INFO "警告: 未找到任何节点"
        rm -f "$temp_proxies"
        echo "[]"
        return
    fi
    
    # 返回合并后的节点
    cat "$temp_proxies"
    rm -f "$temp_proxies"
}

# Get all proxy names
get_proxy_names() {
    grep -E "^\s+- name:" "$1" 2>/dev/null | awk '{print $3}' | tr -d '"' | tr -d "'"
}

# Generate proxy groups
generate_proxy_groups() {
    local temp_file="$1"
    local proxy_names_file="/tmp/proxy_names_$$.txt"
    
    # 获取所有节点名称
    get_proxy_names "$temp_file" > "$proxy_names_file"
    
    if [ ! -s "$proxy_names_file" ]; then
        LOG_INFO "警告: 没有可用的节点"
        rm -f "$proxy_names_file"
        return
    fi
    
    local total_proxies=$(wc -l < "$proxy_names_file")
    LOG_INFO "找到 $total_proxies 个节点"
    
    cat >> "$CONFIG_FILE" << EOF

# Proxy Groups
proxy-groups:
  # 主选组
  - name: 🚀 PROXY
    type: select
    proxies:
      - ♻️ AUTO
      - 🎯 DIRECT
      - 🛑 REJECT
EOF
    
    # 添加所有节点到主选组
    while read -r proxy_name; do
        echo "      - $proxy_name" >> "$CONFIG_FILE"
    done < "$proxy_names_file"
    
    # 自动选择组（URLTest）
    cat >> "$CONFIG_FILE" << EOF
  
  # 自动选择最快节点
  - name: ♻️ AUTO
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
EOF
    
    while read -r proxy_name; do
        echo "      - $proxy_name" >> "$CONFIG_FILE"
    done < "$proxy_names_file"
    
    # 故障转移组
    cat >> "$CONFIG_FILE" << EOF
  
  # 故障转移
  - name: 🔄 FALLBACK
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
EOF
    
    while read -r proxy_name; do
        echo "      - $proxy_name" >> "$CONFIG_FILE"
    done < "$proxy_names_file"
    
    # DIRECT 和 REJECT 组
    cat >> "$CONFIG_FILE" << EOF
  
  # 直连
  - name: 🎯 DIRECT
    type: select
    proxies:
      - DIRECT
  
  # 拒绝
  - name: 🛑 REJECT
    type: select
    proxies:
      - REJECT
EOF
    
    rm -f "$proxy_names_file"
}

# Generate complete configuration
generate_config() {
    mkdir -p "$CONFIG_DIR"
    
    LOG_INFO "开始生成配置文件..."
    
    # Step 1: Generate basic config
    cat > "$CONFIG_FILE" << EOF
# SocksClash v1.2.0 Configuration
# Auto-generated by socks-clash - $(date)

# Port configuration
EOF

    if [ "$mixed_enabled" = "1" ]; then
        echo "mixed-port: $mixed_port" >> "$CONFIG_FILE"
    fi
    
    if [ "$http_enabled" = "1" ]; then
        echo "port: $http_port" >> "$CONFIG_FILE"
    fi
    
    if [ "$socks_enabled" = "1" ]; then
        echo "socks-port: $socks_port" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" << EOF

# LAN access
allow-lan: $([ "$allow_lan" = "1" ] && echo "true" || echo "false")
bind-address: "$bind_address"

# Mode and logging
mode: $mode
log-level: $log_level
ipv6: $([ "$ipv6" = "1" ] && echo "true" || echo "false")

# External controller
external-controller: 0.0.0.0:$cn_port
EOF

    if [ -n "$dashboard_password" ]; then
        echo "secret: \"$dashboard_password\"" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" << EOF

# Profile settings
profile:
  store-selected: true
  store-fake-ip: false

# DNS (disabled for proxy-only mode)
dns:
  enable: false

EOF

    # Step 2: Merge proxies from subscriptions
    local temp_proxies="/tmp/full_proxies_$$.yaml"
    echo "# Proxies" > "$temp_proxies"
    echo "proxies:" >> "$temp_proxies"
    merge_proxies >> "$temp_proxies"
    
    # Add merged proxies to config
    cat "$temp_proxies" >> "$CONFIG_FILE"
    
    # Step 3: Generate proxy groups
    generate_proxy_groups "$temp_proxies"
    
    rm -f "$temp_proxies"
    
    # Step 4: Add rules
    cat >> "$CONFIG_FILE" << EOF

# Rules
rules:
EOF

    # Add custom rules from UCI
    local has_custom_rules=0
    for section in $(uci -q show $UCI_CONFIG | grep "=custom_rule" | cut -d'=' -f1 | cut -d'.' -f2); do
        local rule_enabled=$(uci -q get "$UCI_CONFIG.$section.enabled")
        if [ "$rule_enabled" = "1" ]; then
            local rule_type=$(uci -q get "$UCI_CONFIG.$section.type")
            local rule_value=$(uci -q get "$UCI_CONFIG.$section.value")
            local rule_action=$(uci -q get "$UCI_CONFIG.$section.action")
            if [ -n "$rule_type" ] && [ -n "$rule_value" ] && [ -n "$rule_action" ]; then
                echo "  - $rule_type,$rule_value,$rule_action" >> "$CONFIG_FILE"
                has_custom_rules=1
            fi
        fi
    done
    
    if [ "$has_custom_rules" = "0" ]; then
        LOG_INFO "未找到自定义规则，使用默认规则"
    fi
    
    # Add default rules
    local geoip_cn=$(uci -q get $UCI_CONFIG.config.geoip_cn_direct || echo "1")
    local private_direct=$(uci -q get $UCI_CONFIG.config.private_direct || echo "1")
    local final_rule=$(uci -q get $UCI_CONFIG.config.final_rule || echo "🚀 PROXY")
    
    if [ "$private_direct" = "1" ]; then
        cat >> "$CONFIG_FILE" << EOF
  # 局域网直连
  - IP-CIDR,192.168.0.0/16,🎯 DIRECT
  - IP-CIDR,10.0.0.0/8,🎯 DIRECT
  - IP-CIDR,172.16.0.0/12,🎯 DIRECT
  - IP-CIDR,127.0.0.0/8,🎯 DIRECT
EOF
    fi
    
    if [ "$geoip_cn" = "1" ]; then
        echo "  # 中国 IP 直连" >> "$CONFIG_FILE"
        echo "  - GEOIP,CN,🎯 DIRECT" >> "$CONFIG_FILE"
    fi
    
    echo "  # 默认规则" >> "$CONFIG_FILE"
    echo "  - MATCH,$final_rule" >> "$CONFIG_FILE"
    
    LOG_INFO "配置文件已生成: $CONFIG_FILE"
    
    # Validate config
    if /etc/socks-clash/core/clash -t -d "$CONFIG_DIR" >/dev/null 2>&1; then
        LOG_INFO "配置文件验证成功"
        return 0
    else
        LOG_INFO "警告: 配置文件验证失败，请检查"
        return 1
    fi
}

# Main
load_config
generate_config
