#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/cymfrps
CONF_DIR="/var/etc/cymfrps"

start_instance() {
	local cfg="$1"
	local enabled
	local type
	local content
	local name

	config_get_bool enabled "$cfg" "enabled" 0
	[ "$enabled" -eq 1 ] || return 0

	config_get type "$cfg" "type" "ini"
	config_get content "$cfg" "content"
	
	# Use section name as instance name
	name="$cfg"
	
	mkdir -p "$CONF_DIR"
	local conf_file="$CONF_DIR/$name.$type"
	
	echo "$content" > "$conf_file"

	procd_open_instance "$name"
	procd_set_param command "$PROG" -c "$conf_file"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load cymfrps
	config_foreach start_instance instance
}

service_triggers() {
	procd_add_reload_trigger "cymfrps"
}
