#!/bin/sh
# /etc/uci-defaults/99-panda-luci
# 授予 LuCI 会话访问 panda ACL 组的权限

# 确保 rpcd helper 可执行（部分编译不自动 +x）
chmod +x /usr/libexec/rpcd/luci.panda

uci -q batch <<-EOF
	set rpcd.panda=login
	set rpcd.panda.username=root
	set rpcd.panda.password=\$p\$root
	add_list rpcd.panda.read=luci-app-panda
	add_list rpcd.panda.write=luci-app-panda
EOF
uci commit rpcd

# 重启 rpcd 以加载新的 ACL 和 helper
/etc/init.d/rpcd restart

exit 0
