# Copyright (c) 2026 Eugene Chan
# SPDX-License-Identifier: MIT
# This is free software, licensed under the MIT License.

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-bypass
PKG_VERSION:=1.9.0
PKG_RELEASE:=1
PKG_PO_VERSION:=$(PKG_VERSION)
PKG_LICENSE:=MIT
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=Eugene Chan

# Build-system symbols that, when toggled in menuconfig, should trigger a rebuild.
PKG_CONFIG_DEPENDS:= \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Geoview \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Geo

LUCI_TITLE:=LuCI support for Bypass (NaiveProxy + WireGuard + BypassCore)
LUCI_PKGARCH:=all

# This application only supports fw4/nftables. Keep the firewall userspace and
# kernel expressions as runtime dependencies so installing the generated
# package also installs everything required by REDIRECT and TPROXY modes.
LUCI_DEPENDS:=+ca-bundle +curl +ip-full +resolveip +libubox \
	+nftables +kmod-nft-nat +kmod-nft-tproxy +kmod-nft-socket

define Package/$(PKG_NAME)/config
menu "Configuration"
	depends on PACKAGE_$(PKG_NAME)

config PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy
	bool "Include NaiveProxy (https proxy core)"
	depends on !(arc||armeb||loongarch64||mips||mips64||powerpc||TARGET_gemini)
	select PACKAGE_naiveproxy
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_Geoview
	bool "Include Geoview (geodata query tool)"
	select PACKAGE_geoview
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Geo
	bool "Include v2ray-geoip / v2ray-geosite (geoip.dat / geosite.dat)"
	select PACKAGE_v2ray-geoip
	select PACKAGE_v2ray-geosite
	default n

endmenu
endef

define Package/$(PKG_NAME)/conffiles
/etc/config/bypass
/usr/share/bypass/direct_ip
endef

# OpenWrt's default_postinst synchronously starts every packaged /etc/init.d
# script. Bypass performs readiness checks during start, which can outlive the
# LuCI package-manager RPC and leave it with an empty/truncated JSON response.
# The uci-defaults setup installs/enables the tiny init wrapper from the
# canonical copy under /usr/share, so it is deliberately not packaged directly
# below /etc/init.d and therefore is not auto-started inside opkg.
define Package/$(PKG_NAME)/postinst
	[ -n "$${IPKG_INSTROOT}" ] || { \
		rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
		rm -rf /tmp/luci-modulecache/
		if [ "$$(uci -q get bypass.@global[0].enabled)" = "1" ]; then
			( sleep 2; /etc/init.d/bypass restart ) >/dev/null 2>&1 &
		fi
		exit 0
	}
endef

# /etc/init.d/bypass is generated by uci-defaults and consequently is not in
# opkg's file list. Remove it on a real uninstall, but keep it across upgrades.
define Package/$(PKG_NAME)/prerm
	[ -n "$${IPKG_INSTROOT}" ] || [ "$${PKG_UPGRADE}" = "1" ] || { \
		/etc/init.d/bypass stop >/dev/null 2>&1
		/etc/init.d/bypass disable >/dev/null 2>&1
		rm -f /etc/init.d/bypass
	}
endef

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
