#!/bin/sh
# Kiwi — LuCI ACL 授权（首次启动）
uci -q batch <<-EOF
	set rpcd.kiwi=login
	set rpcd.kiwi.username=root
	set rpcd.kiwi.password=\$p\$root
	add_list rpcd.kiwi.read=luci-app-kiwi
	add_list rpcd.kiwi.write=luci-app-kiwi
EOF
uci commit rpcd

exit 0
