import { defineConfig } from "@rsbuild/core";
import { rspack } from "@rsbuild/core";
// LuCI require statements that must be at the very top of the output file
const luciRequires = `'use strict';
'require firewall as fwmodel';
'require tools.widgets as widgets';
// WARN: generated by rsbuild - do not edit
`;

export default defineConfig({
  resolve: {
    aliasStrategy: "prefer-tsconfig",
  },
  source: {
    entry: {
      config: "./main.tsx",
    },
    tsconfigPath: "./tsconfig.json",
  },
  output: {
    // polyfill: "usage",
    module: true,
    charset: "ascii",
    overrideBrowserslist: [
      "defaults",
      "not ie <= 11",
      "not op_mini all",
      "chrome >= 60",
      "firefox >= 60",
      "safari >= 11",
      "edge >= 16",
    ],
    distPath: {
      root: "../htdocs/luci-static/resources/view/portweaver",
      js: ".",
    },
    filename: {
      js: "[name].js",
    },
    assetPrefix: "",
    minify: false,
    cleanDistPath: true,
  },
  plugins: [],
  tools: {
    htmlPlugin: false,
    swc: {
      jsc: {
        parser: {
          syntax: "typescript",
          tsx: true,
          decorators: true,
        },
        minify: {
          compress: true,
          mangle: {},
        },
        transform: {
          react: {
            runtime: "automatic",
            importSource: "/utils/jsx-factory",
            useBuiltins: true,
          },
          optimizer: {
            simplify: true,
          },
        },
      },
    },
    rspack: (config) => {
      // Configure output for LuCI: simple return statement at module level
      config.output = config.output || {};
      // config.output.iife = true; // No IIFE wrapper

      config.optimization = config.optimization || {};
      config.optimization.splitChunks = false;
      config.optimization.runtimeChunk = false;
      config.optimization.minimize = false;
      config.optimization.avoidEntryIife = true;

      // Use BannerPlugin to inject LuCI requires at the very top
      config.plugins = config.plugins || [];
      config.plugins.push(
        new rspack.BannerPlugin({
          banner: luciRequires,
          raw: true,
          entryOnly: true,
        }),
      );
      config.plugins.push(
        new rspack.BannerPlugin({
          banner: "return main;",
          raw: true,
          entryOnly: true,
          footer: true,
        }),
      );
      return config;
    },
  },
  performance: {
    chunkSplit: {
      strategy: "all-in-one",
    },
  },
});
