#!/bin/sh

# Emit a deterministic, offline inventory of the v2.2.0-4 package baseline.
# Repository files are read from a fixed Git commit and are never executed.

set -eu

DEFAULT_BASELINE_REF=fb272e8285c65415dea8a9a359a4204b94be06a0

usage() {
	printf 'Usage: %s [baseline-ref]\n' "$0"
}

case ${1-} in
-h | --help)
	usage
	exit 0
	;;
-*)
	printf 'error: baseline-ref must not begin with a dash\n' >&2
	exit 2
	;;
esac

if [ "$#" -gt 1 ]; then
	usage >&2
	exit 2
fi

BASELINE_REF=${1:-$DEFAULT_BASELINE_REF}
SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)
export GIT_OPTIONAL_LOCKS=0
export LC_ALL=C

COMMIT=$(git -C "$REPOSITORY" rev-parse --verify "$BASELINE_REF^{commit}") || {
	printf 'error: baseline ref does not resolve to a commit: %s\n' "$BASELINE_REF" >&2
	exit 1
}

git_blob() {
	git -C "$REPOSITORY" cat-file blob "$COMMIT:$1"
}

sha256_blob() {
	if command -v sha256sum >/dev/null 2>&1; then
		git_blob "$1" | sha256sum | awk '{ print $1 }'
	elif command -v shasum >/dev/null 2>&1; then
		git_blob "$1" | shasum -a 256 | awk '{ print $1 }'
	else
		printf 'error: sha256sum or shasum is required\n' >&2
		exit 1
	fi
}

source_mode() {
	git -C "$REPOSITORY" ls-tree "$COMMIT" -- "$1" | awk 'NR == 1 { print $1 }'
}

package_value() {
	git_blob Makefile | sed -n "s/^$1:=//p" | sed -n '1p'
}

case_flags() {
	path=$1
	git_blob "$path" |
		grep -E '^[[:space:]]*--[[:alnum:]-]+([|][^)]*)?\)' 2>/dev/null |
		grep -oE -- '--[[:alnum:]][[:alnum:]-]*' 2>/dev/null |
		sort -u |
		paste -sd ',' -
}

literal_codes() {
	keyword=$1
	path=$2
	git_blob "$path" |
		grep -oE "(^|[[:space:];])${keyword}[[:space:]]+[0-9]+" 2>/dev/null |
		grep -oE '[0-9]+$' 2>/dev/null |
		sort -nu |
		paste -sd ',' -
}

print_inventory_row() {
	role=$1
	source=$2
	destination=$3
	installed_mode=$4
	mode=$(source_mode "$source")

	if [ -z "$mode" ]; then
		printf 'error: baseline path is missing: %s\n' "$source" >&2
		exit 1
	fi

	printf '| %s | `%s` | `%s` | `%s` | `%s` | `%s` |\n' \
		"$role" "$source" "$destination" "$mode" "$installed_mode" "$(sha256_blob "$source")"
}

PACKAGE_NAME=$(package_value PKG_NAME)
PACKAGE_VERSION=$(package_value PKG_VERSION)
PACKAGE_RELEASE=$(package_value PKG_RELEASE)
COMMIT_DATE=$(git -C "$REPOSITORY" show -s --format=%cI "$COMMIT")
COMMIT_SUBJECT=$(git -C "$REPOSITORY" show -s --format=%s "$COMMIT")

printf '%s\n' '# MultiLogin v2.2.0-4 deterministic baseline'
printf '\n'
printf '%s\n' '<!-- Generated by tools/v3-baseline.sh. Do not edit by hand. -->'
printf '\n'
printf '%s\n' 'This report inventories source objects only. It performs no portal, network, service, package, or device action. UCI credential examples are redacted by field name.'
printf '\n'
printf '%s\n' '## Source identity'
printf '\n'
printf -- '- Git commit: `%s`\n' "$COMMIT"
printf -- '- Commit date: `%s`\n' "$COMMIT_DATE"
printf -- '- Commit subject: `%s`\n' "$COMMIT_SUBJECT"
printf -- '- Package: `%s`\n' "$PACKAGE_NAME"
printf -- '- Version: `%s-%s`\n' "$PACKAGE_VERSION" "$PACKAGE_RELEASE"
printf -- '- Reproduce: `sh tools/v3-baseline.sh %s`\n' "$COMMIT"
printf -- '- Verify: `sh tools/v3-baseline.sh %s | cmp - docs/v3/baseline-v2.2.0-4.txt`\n' "$COMMIT"
printf '\n'
printf '%s\n' '## Tracked package and control inventory'
printf '\n'
printf '%s\n' '| Role | Source path | Package path | Git mode | Package mode | SHA-256 |'
printf '%s\n' '| --- | --- | --- | --- | --- | --- |'
print_inventory_row control Makefile '(build control)' n/a
print_inventory_row config etc/config/multilogin /etc/config/multilogin 0600
print_inventory_row init etc/init.d/multilogin /etc/init.d/multilogin 0755
print_inventory_row action etc/multilogin/check_status.sh /etc/multilogin/check_status.sh 0755
print_inventory_row action etc/multilogin/login.sh /etc/multilogin/login.sh 0755
print_inventory_row action etc/multilogin/login_A.sh /etc/multilogin/login_A.sh 0755
print_inventory_row controller etc/multilogin/login_control.bash /etc/multilogin/login_control.bash 0755
print_inventory_row action etc/multilogin/login_huxi.sh /etc/multilogin/login_huxi.sh 0755
print_inventory_row action etc/multilogin/logout.sh /etc/multilogin/logout.sh 0755
print_inventory_row helper etc/multilogin/quick_setup.sh /etc/multilogin/quick_setup.sh 0755
print_inventory_row view htdocs/luci-static/resources/view/multilogin/accounts.js /www/luci-static/resources/view/multilogin/accounts.js 0644
print_inventory_row view htdocs/luci-static/resources/view/multilogin/interfaces.js /www/luci-static/resources/view/multilogin/interfaces.js 0644
print_inventory_row view htdocs/luci-static/resources/view/multilogin/log.js /www/luci-static/resources/view/multilogin/log.js 0644
print_inventory_row view htdocs/luci-static/resources/view/multilogin/script.js /www/luci-static/resources/view/multilogin/script.js 0644
print_inventory_row view htdocs/luci-static/resources/view/multilogin/settings.js /www/luci-static/resources/view/multilogin/settings.js 0644
print_inventory_row rpcd root/usr/libexec/rpcd/multilogin /usr/libexec/rpcd/multilogin 0755
print_inventory_row menu root/usr/share/luci/menu.d/luci-app-multi-login.json /usr/share/luci/menu.d/luci-app-multi-login.json 0644
print_inventory_row acl root/usr/share/rpcd/acl.d/luci-app-multi-login.json /usr/share/rpcd/acl.d/luci-app-multi-login.json 0644
printf '\n'
printf '%s\n' 'Package paths and modes above are derived from the `INSTALL_BIN`, `INSTALL_DATA`, and `INSTALL_CONF` operations in the pinned Makefile; Git modes record the source tree independently.'
printf '\n'
printf '%s\n' '## UCI schema and stock defaults'
printf '\n'
printf '%s\n' '| Section type | Stock section | Option | Stock default |'
printf '%s\n' '| --- | --- | --- | --- |'
git_blob etc/config/multilogin | awk '
	function unquote(value, first, last) {
		first = substr(value, 1, 1)
		last = substr(value, length(value), 1)
		if ((first == "\"" && last == "\"") || (first == sprintf("%c", 39) && last == sprintf("%c", 39)))
			return substr(value, 2, length(value) - 2)
		return value
	}
	$1 == "config" {
		section_type = unquote($2)
		section_name = unquote($3)
		next
	}
	$1 == "option" {
		option_name = unquote($2)
		value = $0
		sub(/^[[:space:]]*option[[:space:]]+[^[:space:]]+[[:space:]]+/, "", value)
		value = unquote(value)
		if (option_name == "username" || option_name == "password")
			value = "<redacted-example>"
		printf "| `%s` | `%s` | `%s` | `%s` |\n", section_type, section_name, option_name, value
	}'
printf '\n'
printf '%s\n' 'The schema contains named `settings.global`, `account`, and `instance` sections. The displayed account credential defaults are placeholders with their values intentionally omitted.'
printf '\n'
printf '%s\n' '## rpcd advertised methods and parameters'
printf '\n'
printf '%s\n' 'The exact `list` response embedded in `/usr/libexec/rpcd/multilogin` is:'
printf '\n'
printf '%s\n' '```json'
git_blob root/usr/libexec/rpcd/multilogin |
	sed -n '/printf.*{"quick_setup"/ { s/^[^{]*//; s/\\n.*$//; p; q; }'
printf '%s\n' '```'
printf '\n'
printf '%s\n' 'The rpcd executable accepts dispatcher actions `list` and `call`; unknown dispatcher actions or methods exit with literal status 1.'
printf '\n'
printf '%s\n' '## Package and service lifecycle'
printf '\n'
for hook in preinst install postinst prerm postrm; do
	if git_blob Makefile | grep -q "^define Package/$PACKAGE_NAME/$hook$"; then
		printf -- '- Package hook `%s`: present\n' "$hook"
	else
		printf -- '- Package hook `%s`: absent\n' "$hook"
	fi
done
printf '\n'
printf '%s\n' 'Init constants and hooks:'
printf '\n'
printf '%s\n' '```text'
git_blob etc/init.d/multilogin | awk -F= '
	/^(START|STOP|USE_PROCD|PROG)=/ { print $0 }
	/^[[:alnum:]_]+\(\)[[:space:]]*\{/ {
		name = $0
		sub(/\(.*/, "", name)
		print "hook=" name
	}'
printf '%s\n' '```'
printf '\n'
printf '%s\n' 'procd calls made by the init script:'
printf '\n'
printf '%s\n' '```text'
git_blob etc/init.d/multilogin |
	sed -n '/^[[:space:]]*procd_/ { s/^[[:space:]]*//; p; }'
printf '%s\n' '```'
printf '\n'
printf '%s\n' 'Static Makefile behavior: live-root `postinst` enables MultiLogin and restarts rpcd; live-root `prerm` stops/disables MultiLogin and restarts rpcd; live-root `postrm` removes matching rc.d links. Each live-root block is skipped when `IPKG_INSTROOT` is set.'
printf '\n'
printf '%s\n' '## Legacy action-script surface'
printf '\n'
printf '%s\n' '| Source | Recognized or mentioned long flags | Literal `exit` codes | Literal function `return` codes |'
printf '%s\n' '| --- | --- | --- | --- |'
for action_path in \
	etc/multilogin/login.sh \
	etc/multilogin/login_huxi.sh \
	etc/multilogin/login_A.sh \
	etc/multilogin/check_status.sh \
	etc/multilogin/logout.sh \
	etc/multilogin/quick_setup.sh; do
	flags=$(case_flags "$action_path")
	if [ "$action_path" = etc/multilogin/check_status.sh ]; then
		flags='--check-only (plus pass-through)'
	fi
	exits=$(literal_codes exit "$action_path")
	returns=$(literal_codes return "$action_path")
	[ -n "$flags" ] || flags='(none; positional or pass-through)'
	[ -n "$exits" ] || exits='(none; delegated)'
	[ -n "$returns" ] || returns='(none)'
	printf '| `%s` | `%s` | `%s` | `%s` |\n' "$action_path" "$flags" "$exits" "$returns"
done
printf '\n'
printf '%s\n' 'Static relationships: `check_status.sh` forwards all arguments to `login.sh` and appends `--check-only`; `login.sh` and `login_huxi.sh` have the same SHA-256. `quick_setup.sh` uses positional `<base_interface> <count>` arguments. The table intentionally records only literal status values; semantic compatibility is frozen in the v3 contract.'
printf '\n'
printf '%s\n' '## LuCI menu surface (exact baseline JSON)'
printf '\n'
printf '%s\n' '```json'
git_blob root/usr/share/luci/menu.d/luci-app-multi-login.json
printf '\n%s\n' '```'
printf '\n'
printf '%s\n' '## rpcd ACL surface (exact baseline JSON)'
printf '\n'
printf '%s\n' '```json'
git_blob root/usr/share/rpcd/acl.d/luci-app-multi-login.json
printf '\n%s\n' '```'
