#!/bin/sh /etc/rc.common

START=99
STOP=90
USE_PROCD=1

dir="/tmp/pushbot/"

remove_pushbot_cron() {
	del_cron() {
		crontab -l  2>/dev/null | grep -v "pushbot" | crontab -
	}
	re_cron() {
  		/etc/init.d/cron stop
  		/etc/init.d/cron start
  	}
  del_cron
  re_cron
  return 0
}


start_service() {
    enable_value=$(uci get pushbot.pushbot.pushbot_enable 2>/dev/null || echo "0")

    # 只有在启用时才创建实例
    if [ "$enable_value" -ne "0" ]; then
        # 确保目录存在
        mkdir -p $dir

        procd_open_instance
        procd_set_param command /usr/bin/pushbot/pushbot  "daemon"

        # 添加重启参数
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

        # 重定向日志
        procd_set_param stdout 1
        procd_set_param stderr 1

        # 设置工作目录
        procd_set_param file /etc/config/pushbot
        procd_set_param pidfile /var/run/pushbot.pid

        procd_close_instance
        echo "pushbot is starting now ..."
    else
        echo "pushbot is disabled, not starting"
    fi
}

reload_service() {
    stop
    sleep 1
    start
    echo "pushbot restarted successfully.."
}

stop_service() {
    logger -t pushbot "stopping pushbot"
    pgrep -f "/usr/bin/pushbot/pushbot" | xargs kill -9
    remove_pushbot_cron
    logger -t pushbot "clean pushbot cron"
    # 清理锁
    rm -f /tmp/pushbot/pushbot_daemon_running.lock
    logger -t pushbot "remove pushbot daemon running lock"
    logger -t pushbot "pushbot stopped"
    echo "pushbot stopped"
}

service_triggers() {
    procd_add_reload_trigger pushbot
}