#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Smart >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Smart=/luci-static/smart
		set luci.main.mediaurlbase=/luci-static/smart
		commit luci
	EOF
fi

exit 0