'use strict';
'require baseclass';

/* Argon-only QDDNS styling. Dark rules use the computed-mode marker from theme.js. */
var ARGON_CSS = [
	'.qddns-theme-argon{',
		'--qddns-radius-sm:.25rem;',
		'--qddns-radius-md:.25rem;',
		'--qddns-border:var(--lighter,#e9ecef);',
		'--qddns-surface:var(--white,#fff);',
		'--qddns-surface-strong:#f6f9fc;',
		'--qddns-positive:rgba(45,206,137,.16);',
		'--qddns-positive-text:#17764f;',
		'--qddns-negative:rgba(245,54,92,.14);',
		'--qddns-negative-text:#ae2040;',
		'--qddns-warning:rgba(251,99,64,.16);',
		'--qddns-warning-text:#a43b25;',
		'--qddns-neutral:rgba(136,152,170,.14);',
		'--qddns-neutral-text:var(--gray-dark,#32325d);',
	'}',
	'.qddns-theme-argon.qddns-dashboard,.qddns-theme-argon.qddns-rules-page,.qddns-theme-argon.qddns-settings-page,.qddns-theme-argon.qddns-logs-page{display:flex;flex-direction:column;gap:1rem;margin-bottom:1rem}',
	'.qddns-theme-argon .qddns-panel,.qddns-theme-argon .qddns-card{box-sizing:border-box;margin-bottom:0;border:0;border-radius:.25rem;background:var(--white,#fff);box-shadow:0 0 1rem rgba(136,152,170,.15);overflow:hidden}',
	'.qddns-theme-argon.qddns-dashboard>.qddns-panel{margin-bottom:0}',
	'.qddns-theme-argon .qddns-panel{padding:0}',
	'.qddns-theme-argon .qddns-form-panel{background:transparent;box-shadow:none;overflow:visible}',
	'.qddns-theme-argon .qddns-page-header{padding:1.05rem 1.25rem;border-left:3px solid var(--primary,#5e72e4)}',
	'.qddns-theme-argon .qddns-page-title{margin:0;padding:0;border-radius:0;background:transparent;box-shadow:none;color:var(--gray-dark,#32325d);font-size:1.35rem;line-height:1.25!important}',
	'.qddns-theme-argon .qddns-page-desc{margin:0;padding:0;color:var(--gray,#8898aa);font-size:.9rem;line-height:1.5;opacity:1}',
	'.qddns-theme-argon .qddns-page-cta-text h3{width:auto;padding:0;border-radius:0;background:transparent;box-shadow:none;line-height:1.3!important}',
	'.qddns-theme-argon .qddns-page-cta-text p{padding:0}',
	'.qddns-theme-argon .qddns-ip-synced{flex-wrap:wrap;white-space:normal}',
	'.qddns-theme-argon .qddns-actions .cbi-button{height:auto;min-height:2.5rem}',
	'.qddns-theme-argon .alert-message{box-sizing:border-box;position:static;left:auto;top:auto;width:auto;max-width:100%;transform:none}',
	'.qddns-theme-argon .qddns-rule-wizard-feedback.alert-message.warning{background:var(--qddns-warning)!important;color:var(--qddns-warning-text)}',
	'.qddns-theme-argon .qddns-page-cta{padding:1rem 1.25rem}',
	'.qddns-theme-argon .qddns-panel>.qddns-actions{padding:0 1.25rem 1.25rem}',
	'.qddns-theme-argon .qddns-panel>.qddns-log-output{margin:0 1.25rem 1.25rem}',
	'.qddns-theme-argon .qddns-card{min-height:7rem;padding:1rem 1.25rem;justify-content:space-between}',
	'.qddns-theme-argon .qddns-card-label{color:var(--gray,#8898aa);font-size:.78rem;font-weight:600;letter-spacing:.035em;opacity:1;text-transform:uppercase}',
	'.qddns-theme-argon .qddns-card-value{color:var(--default,#172b4d);font-size:1.55rem}',
	'.qddns-theme-argon .qddns-badge{box-sizing:border-box;min-height:1.75rem;padding:.3rem .7rem;border:0;font-size:.78rem;line-height:1.15}',
	'.qddns-theme-argon .qddns-log-output{border-color:var(--lighter,#e9ecef);background:#f6f9fc;color:var(--default,#172b4d);font-family:ui-monospace,"SFMono-Regular",Consolas,monospace}',
	'.qddns-theme-argon .qddns-lease-card{height:auto;min-height:0;border-color:var(--lighter,#e9ecef);border-radius:.25rem;background:#f6f9fc;box-shadow:0 2px 5px rgba(50,50,93,.08);transition:border-color .15s ease,box-shadow .15s ease}',
	'.qddns-theme-argon .qddns-lease-card:hover,.qddns-theme-argon .qddns-lease-card:focus-visible,.qddns-theme-argon .qddns-lease-card.is-selected{border-color:var(--primary,#5e72e4);background:rgba(94,114,228,.08);box-shadow:0 0 0 2px rgba(94,114,228,.18);outline:none}',
	'.qddns-theme-argon .qddns-lease-action{background:rgba(94,114,228,.12);color:var(--primary,#5e72e4);opacity:1}',
	'.qddns-theme-argon .qddns-rule-wizard-primary{height:auto;min-height:2.5rem;padding:.55rem .85rem}',
	'.qddns-theme-argon .qddns-rule-wizard-step{border-color:var(--lighter,#e9ecef);border-radius:.25rem;background:#f6f9fc;color:var(--gray,#8898aa)}',
	'.qddns-theme-argon .qddns-rule-wizard-step.is-active{border-color:var(--primary,#5e72e4);background:rgba(94,114,228,.1);color:var(--primary,#5e72e4);box-shadow:inset 3px 0 var(--primary,#5e72e4)}',
	'.qddns-theme-argon .qddns-rule-wizard-step.is-complete{border-color:transparent;background:var(--qddns-positive);color:var(--qddns-positive-text)}',
	'.qddns-theme-argon .qddns-rule-wizard-section{border-color:var(--lighter,#e9ecef);border-radius:.25rem;background:#f6f9fc}',
	'.qddns-theme-argon .qddns-rule-wizard-summary,.qddns-theme-argon .qddns-rule-wizard-source-status{border-color:var(--lighter,#e9ecef);background:var(--white,#fff)}',
	'.qddns-theme-argon.modal.qddns-rule-wizard-dialog{width:min(64rem,94vw);max-width:none;margin:.5rem auto;border-radius:.25rem!important;background:var(--white,#fff);box-shadow:0 2px 12px rgba(0,0,0,.18)}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon{',
		'--qddns-border:#3c3c3c;',
		'--qddns-surface:#1e1e1e;',
		'--qddns-surface-strong:#252526;',
		'--qddns-positive:rgba(45,206,137,.2);',
		'--qddns-positive-text:#8ae5bd;',
		'--qddns-negative:rgba(245,54,92,.22);',
		'--qddns-negative-text:#ff9eb1;',
		'--qddns-warning:rgba(251,99,64,.22);',
		'--qddns-warning-text:#ffb09e;',
		'--qddns-neutral:#333;',
		'--qddns-neutral-text:#ccc;',
		'color:#ccc;',
	'}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-panel{background:#1e1e1e!important;box-shadow:0 0 .5rem rgba(0,0,0,.35)}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-form-panel{background:transparent!important;box-shadow:none}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-card{background:#252526!important;box-shadow:0 0 .5rem rgba(0,0,0,.35)}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-page-title,html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-card-value{color:#ccc}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-page-desc,html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-card-label{color:#adb5bd}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-log-output{border-color:#3c3c3c;background:#252526;color:#ccc}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-lease-card{border-color:#3c3c3c;background:#252526;color:#ccc;box-shadow:0 2px 5px rgba(0,0,0,.3)}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-lease-card:hover,html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-lease-card:focus-visible,html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-lease-card.is-selected{border-color:var(--dark-primary,#483d8b)!important;background:#333}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-lease-action{background:var(--dark-primary,#483d8b);color:#fff}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-rule-wizard-step,html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-rule-wizard-section{border-color:#3c3c3c;background:#252526;color:#ccc}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-rule-wizard-step.is-active{border-color:var(--dark-primary,#483d8b);background:#333;color:#fff;box-shadow:inset 3px 0 var(--dark-primary,#483d8b)}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-rule-wizard-summary,html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-rule-wizard-source-status{border-color:#3c3c3c;background:#1e1e1e}',
	'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon.modal.qddns-rule-wizard-dialog{background:#1e1e1e!important;box-shadow:0 2px 12px rgba(0,0,0,.5)}',
	'@media (max-width:1152px){',
		'.qddns-theme-argon .qddns-table-wrap{box-sizing:border-box;padding:.75rem;overflow:visible}',
		'.qddns-theme-argon .qddns-table-wrap .qddns-table,.qddns-theme-argon .qddns-rules-console-table .qddns-table,.qddns-theme-argon .qddns-wide-form .cbi-section-table{min-width:0}',
		'.qddns-theme-argon .qddns-wide-form{overflow:visible}',
		'.qddns-theme-argon .qddns-table-wrap .qddns-table td{max-width:100%;min-width:0;white-space:normal}',
		'.qddns-theme-argon .qddns-table-wrap .qddns-ip-synced{box-sizing:border-box;display:flex;width:100%;max-width:100%;min-width:0;flex-wrap:wrap;overflow-wrap:anywhere;white-space:normal}',
		'.qddns-theme-argon .cbi-section-table td.cbi-section-actions{box-sizing:border-box;flex:0 0 100%;width:auto!important;min-width:0!important;max-width:100%;white-space:normal}',
		'.qddns-theme-argon .cbi-section-table td.cbi-section-actions>div{box-sizing:border-box;display:flex;width:100%;max-width:100%;min-width:0;flex-wrap:wrap;gap:.5rem}',
		'.qddns-theme-argon .cbi-section-table td.cbi-section-actions .cbi-button{flex:1 1 auto;min-width:0;max-width:100%;margin:0}',
		'.qddns-theme-argon .qddns-table-row{box-sizing:border-box;margin-bottom:.75rem;padding:.65rem;border-radius:.25rem;background:#f6f9fc;box-shadow:0 2px 5px rgba(50,50,93,.08)}',
		'.qddns-theme-argon .qddns-table-row:last-child{margin-bottom:0}',
		'.qddns-theme-argon .qddns-table-row>.td{box-sizing:border-box;flex:1 1 50%;min-width:0;padding:.55rem .65rem;text-align:left}',
		'.qddns-theme-argon .qddns-table-row>.td:last-child{flex-basis:100%;width:auto;min-width:0}',
		'.qddns-theme-argon .qddns-table-row-empty>.qddns-empty-cell{flex:0 0 100%}',
		'.qddns-theme-argon .qddns-rules-form.qddns-wide-form .cbi-section-table th,.qddns-theme-argon .qddns-rules-form.qddns-wide-form .cbi-section-table td{width:auto;min-width:0;white-space:normal}',
		'.qddns-theme-argon .qddns-rules-console-table .qddns-actions{flex-wrap:wrap}',
		'html[data-qddns-theme="argon"][data-qddns-dark="true"] .qddns-theme-argon .qddns-table-row{background:#252526;box-shadow:0 2px 5px rgba(0,0,0,.3)}',
	'}',
	'@media (max-width:600px){',
		'.qddns-theme-argon.qddns-dashboard,.qddns-theme-argon.qddns-rules-page,.qddns-theme-argon.qddns-settings-page,.qddns-theme-argon.qddns-logs-page{gap:.75rem}',
		'.qddns-theme-argon .qddns-page-header{padding:.9rem 1rem}',
		'.qddns-theme-argon .qddns-page-cta{padding:.9rem 1rem}',
		'.qddns-theme-argon .qddns-card{padding:.9rem 1rem}',
		'.qddns-theme-argon .qddns-panel>.qddns-actions{padding:0 1rem 1rem}',
		'.qddns-theme-argon .qddns-panel>.qddns-log-output{margin:0 1rem 1rem}',
		'.qddns-theme-argon .qddns-panel>.cbi-value{display:grid;gap:.25rem;padding:.55rem 1rem;line-height:1.5}',
		'.qddns-theme-argon .qddns-panel>.cbi-value>.cbi-value-title{float:none;width:100%;padding:0;text-align:left}',
		'.qddns-theme-argon .qddns-panel>.cbi-value>.cbi-value-field{display:block;width:100%}',
		'.qddns-theme-argon .qddns-panel>.cbi-value>.cbi-value-field>.cbi-input-text,.qddns-theme-argon .qddns-panel>.cbi-value>.cbi-value-field>.cbi-input-select{box-sizing:border-box;width:100%!important;min-width:0;max-width:none}',
		'.qddns-theme-argon .cbi-section-create{display:flex;flex-direction:column;align-items:stretch;gap:.5rem}',
		'.qddns-theme-argon .cbi-section-create>div{width:100%}',
		'.qddns-theme-argon .cbi-section-create>.cbi-button{width:100%!important;height:auto;min-height:2.5rem;margin:0;border-radius:.25rem}',
		'.qddns-theme-argon .qddns-table-row>.td{flex-basis:100%}',
		'.qddns-theme-argon.modal.qddns-rule-wizard-dialog{width:calc(100vw - 1.25rem);max-height:calc(100dvh - 1.25rem);margin:.625rem auto;padding:1rem}',
	'}',
	'@media (max-width:480px){',
		'.qddns-theme-argon .qddns-cards{grid-template-columns:1fr}',
		'.qddns-theme-argon .qddns-card{min-height:5.25rem}',
		'.qddns-theme-argon .qddns-page-cta>.cbi-button,.qddns-theme-argon .qddns-actions>.cbi-button{flex:1 1 100%;width:100%!important}',
		'.qddns-theme-argon .qddns-actions>.cbi-input-select{width:100%!important;max-width:none}',
		'.qddns-theme-argon .qddns-rule-wizard-footer-actions>.cbi-button{flex:1 1 100%;width:100%!important}',
		'.qddns-theme-argon .qddns-lease-head,.qddns-theme-argon .qddns-lease-meta-item{grid-template-columns:1fr}',
		'.qddns-theme-argon .qddns-lease-action{justify-self:start}',
	'}'
].join('');

return baseclass.extend({
	CSS: ARGON_CSS
});
