'use strict';
'require baseclass';

/* Aurora-only QDDNS styling. Every rule is scoped to the detected theme root. */
var AURORA_CSS = [
	'.qddns-theme-aurora{',
		'--qddns-radius-sm:var(--radius-base,.5rem);',
		'--qddns-radius-md:calc(var(--radius-base,.5rem)*2);',
		'--qddns-border:var(--hairline,rgba(18,26,34,.13));',
		'--qddns-surface:var(--surface,#fff);',
		'--qddns-surface-strong:var(--surface-sunken,#f4f7fa);',
		'--qddns-positive:var(--success-surface,#d3f8eb);',
		'--qddns-positive-text:var(--success,#004f3e);',
		'--qddns-negative:var(--danger-surface,#ffe8e6);',
		'--qddns-negative-text:var(--danger,#8d1925);',
		'--qddns-warning:var(--warning-surface,#ffedd6);',
		'--qddns-warning-text:var(--warning,#643e00);',
		'--qddns-neutral:var(--surface-sunken,#f4f7fa);',
		'--qddns-neutral-text:var(--text-muted,#5f666d);',
		'color:var(--text,#121a22);',
	'}',
	'.qddns-theme-aurora.qddns-dashboard,.qddns-theme-aurora.qddns-rules-page,.qddns-theme-aurora.qddns-settings-page,.qddns-theme-aurora.qddns-logs-page{display:flex;flex-direction:column;gap:1rem;margin-bottom:1.5rem}',
	'.qddns-theme-aurora .qddns-panel,.qddns-theme-aurora .qddns-card{box-sizing:border-box;margin-bottom:0;border-color:var(--hairline);border-radius:calc(var(--radius-base)*2);background:var(--surface);box-shadow:var(--app-shadow-sm)}',
	'.qddns-theme-aurora.qddns-dashboard>.qddns-panel{margin-bottom:0}',
	'.qddns-theme-aurora .qddns-form-panel{padding:0;border:0;background:transparent;box-shadow:none}',
	'.qddns-theme-aurora .qddns-page-header{padding:1.15rem 1.25rem;border-left:3px solid var(--brand)}',
	'.qddns-theme-aurora .qddns-page-title{padding:0;color:var(--text);font-size:var(--text-xl,1.25rem);letter-spacing:-.0125em}',
	'.qddns-theme-aurora .qddns-page-desc{color:var(--text-muted);opacity:1}',
	'.qddns-theme-aurora .qddns-page-cta-text h3{border:0;padding:0}',
	'.qddns-theme-aurora .alert-message{position:static;top:auto;z-index:auto}',
	'.qddns-theme-aurora .qddns-ip-synced{flex-wrap:wrap;white-space:normal}',
	'.qddns-theme-aurora .qddns-card{min-height:7rem;padding:1.15rem 1.25rem;justify-content:space-between;transition:transform .15s ease,box-shadow .15s ease}',
	'.qddns-theme-aurora .qddns-card-label{color:var(--text-subtle);font-size:var(--text-xs,.75rem);font-weight:600;letter-spacing:.04em;opacity:1;text-transform:uppercase}',
	'.qddns-theme-aurora .qddns-card-value{color:var(--text);font-size:var(--text-2xl,1.5rem)}',
	'.qddns-theme-aurora .qddns-badge{min-height:1.75rem;padding:.2rem .7rem;border-color:transparent;font-size:var(--text-xs,.75rem)}',
	'.qddns-theme-aurora .qddns-badge-positive{background:var(--success-surface);color:var(--success)}',
	'.qddns-theme-aurora .qddns-badge-negative{background:var(--danger-surface);color:var(--danger)}',
	'.qddns-theme-aurora .qddns-badge-warning{background:var(--warning-surface);color:var(--warning)}',
	'.qddns-theme-aurora .qddns-badge-neutral{border-color:var(--hairline);background:var(--surface-sunken);color:var(--text-muted)}',
	'.qddns-theme-aurora .qddns-log-output{border-color:var(--hairline);background:var(--control-bg,var(--surface-sunken));color:var(--text);font-family:var(--font-mono,monospace)}',
	'.qddns-theme-aurora .qddns-lease-card{border-color:var(--hairline);border-radius:calc(var(--radius-base)*1.5);background:var(--surface-sunken);box-shadow:var(--app-shadow-sm);transition:border-color .15s ease,background-color .15s ease,box-shadow .15s ease}',
	'.qddns-theme-aurora .qddns-lease-card:hover,.qddns-theme-aurora .qddns-lease-card:focus-visible,.qddns-theme-aurora .qddns-lease-card.is-selected{border-color:var(--brand);background:var(--brand-subtle);box-shadow:0 0 0 3px var(--focus-ring);outline:none}',
	'.qddns-theme-aurora .qddns-lease-action{background:var(--brand-subtle);color:var(--brand);opacity:1}',
	'.qddns-theme-aurora .qddns-rule-wizard-step{border-color:var(--hairline);border-radius:var(--radius-base);background:var(--surface-sunken);color:var(--text-muted)}',
	'.qddns-theme-aurora .qddns-rule-wizard-step.is-active{border-color:var(--brand);background:var(--brand-subtle);color:var(--brand)}',
	'.qddns-theme-aurora .qddns-rule-wizard-step.is-complete{border-color:transparent;background:var(--success-surface);color:var(--success)}',
	'.qddns-theme-aurora .qddns-rule-wizard-section{border-color:var(--hairline);border-radius:calc(var(--radius-base)*1.5);background:var(--surface-sunken)}',
	'.qddns-theme-aurora .qddns-rule-wizard-summary,.qddns-theme-aurora .qddns-rule-wizard-source-status{border-color:var(--hairline);background:var(--surface)}',
	'.qddns-theme-aurora.modal.qddns-rule-wizard-dialog{width:min(64rem,94vw);border-color:var(--hairline);border-radius:calc(var(--radius-base)*3);background:var(--surface-overlay);box-shadow:var(--app-shadow-lg)}',
	'html[data-qddns-theme="aurora"][data-darkmode="true"] .qddns-theme-aurora .qddns-card{background:var(--surface-overlay)}',
	'html[data-qddns-theme="aurora"][data-darkmode="true"] .qddns-theme-aurora .qddns-log-output{background:var(--control-bg)}',
	'@media (hover:hover){.qddns-theme-aurora .qddns-card:hover{transform:translateY(-1px);box-shadow:var(--app-shadow-md)}}',
	'@media (max-width:767px){',
		'.qddns-theme-aurora.qddns-dashboard,.qddns-theme-aurora.qddns-rules-page,.qddns-theme-aurora.qddns-settings-page,.qddns-theme-aurora.qddns-logs-page{gap:.75rem;margin-bottom:1rem}',
		'.qddns-theme-aurora .qddns-panel,.qddns-theme-aurora .qddns-card{padding:.85rem 1rem;border-radius:calc(var(--radius-base)*1.5)}',
		'.qddns-theme-aurora .qddns-form-panel{padding:0}',
		'.qddns-theme-aurora .qddns-page-header{padding:.9rem 1rem}',
		'.qddns-theme-aurora .qddns-table-wrap{overflow:visible}',
		'.qddns-theme-aurora .qddns-table-wrap .qddns-table,.qddns-theme-aurora .qddns-rules-console-table .qddns-table,.qddns-theme-aurora .qddns-wide-form .cbi-section-table{min-width:0}',
		'.qddns-theme-aurora .qddns-wide-form{overflow:visible}',
		'.qddns-theme-aurora .qddns-table-wrap .qddns-table td{max-width:100%;min-width:0;white-space:normal}',
		'.qddns-theme-aurora .qddns-table-wrap .qddns-ip-synced{box-sizing:border-box;display:flex;width:100%;max-width:100%;min-width:0;flex-wrap:wrap;overflow-wrap:anywhere;white-space:normal}',
		'.qddns-theme-aurora .cbi-section-table td.cbi-section-actions{box-sizing:border-box;flex:0 0 100%;width:auto!important;min-width:0!important;max-width:100%;white-space:normal}',
		'.qddns-theme-aurora .cbi-section-table td.cbi-section-actions>div{box-sizing:border-box;display:flex;width:100%;max-width:100%;min-width:0;flex-wrap:wrap;gap:.5rem}',
		'.qddns-theme-aurora .cbi-section-table td.cbi-section-actions .cbi-button{flex:1 1 auto;min-width:0;max-width:100%;margin:0}',
		'.qddns-theme-aurora .qddns-table-row-empty>.qddns-empty-cell{flex:0 0 100%}',
		'.qddns-theme-aurora .qddns-table-row>.td:last-child{flex:0 0 100%;width:auto;min-width:0}',
		'.qddns-theme-aurora .qddns-rules-form.qddns-wide-form .cbi-section-table td:last-child{width:auto;min-width:0;white-space:normal}',
		'.qddns-theme-aurora .qddns-rules-console-table .qddns-actions{flex-wrap:wrap}',
		'.qddns-theme-aurora.modal.qddns-rule-wizard-dialog{width:calc(100vw - 1.5rem);max-width:none;max-height:calc(100dvh - 1.5rem);padding:1rem;border-radius:calc(var(--radius-base)*2)}',
	'}',
	'@media (max-width:480px){',
		'.qddns-theme-aurora .qddns-cards{grid-template-columns:1fr}',
		'.qddns-theme-aurora .qddns-card{min-height:5.25rem}',
		'.qddns-theme-aurora .qddns-page-cta>.cbi-button,.qddns-theme-aurora .qddns-actions>.cbi-button{flex:1 1 100%;width:100%}',
		'.qddns-theme-aurora .qddns-actions>.cbi-input-select{width:100%;max-width:none}',
		'.qddns-theme-aurora .qddns-rule-wizard-footer-actions>.cbi-button{flex:1 1 100%}',
		'.qddns-theme-aurora .qddns-lease-head,.qddns-theme-aurora .qddns-lease-meta-item{grid-template-columns:1fr}',
		'.qddns-theme-aurora .qddns-lease-action{justify-self:start}',
	'}'
].join('');

return baseclass.extend({
	CSS: AURORA_CSS
});
