#!/bin/sh /etc/rc.common
# 咪咕直播源转发服务
START=99
STOP=10

USE_PROCD=1
PROG=/usr/share/ucode/migu.uc
NAME=migu

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/ucode "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "migu"
}

reload_service() {
	stop
	start
}
