include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Network Setup Wizard
LUCI_DEPENDS:=+luci-base
PKG_VERSION:=1.3.1
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
