#!/bin/sh
# Register bandix-plus UCI changes with LuCI's apply mechanism so that
# saving the form automatically reloads /etc/init.d/bandix-plus.

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@bandix-plus[-1]
	add ucitrack bandix-plus
	set ucitrack.@bandix-plus[-1].init=bandix-plus
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache /tmp/luci-modulecache/* 2>/dev/null
exit 0
