#!/bin/sh /etc/rc.common
# Copyright (C) 2026 huchd0 <https://github.com/huchd0/luci-app-netwiz>
# Licensed under the GNU General Public License v3.0

START=15

boot() {
    if [ -f /etc/config/network.netwiz_bak ]; then
        logger -t Netwiz "Power loss detected during test! Forcefully recovering network..."
        
        cp /etc/config/network.netwiz_bak /etc/config/network
        cp /etc/config/dhcp.netwiz_bak /etc/config/dhcp
        

        rm -f /etc/config/network.netwiz_bak /etc/config/dhcp.netwiz_bak
        rm -f /tmp/netwiz_rollback_time /tmp/netwiz_target_ip
        
    fi
}
