#!/bin/sh
# Copyright (C) 2026 huchd0 <https://github.com/huchd0/luci-app-netwiz>
# Licensed under the GNU General Public License v3.0

[ "$ACTION" = "change" ] || [ "$ACTION" = "add" ] || exit 0

/usr/libexec/netwiz-autodetect.sh >/dev/null 2>&1 </dev/null &
