#!/bin/sh
# luci-app-clawpanel - UCI defaults
# 首次安装时初始化 UCI 配置

. /lib/functions.sh

if [ -z "$(uci get clawpanel.main 2>/dev/null)" ]; then
    uci add clawpanel main >/dev/null 2>&1
fi

uci set clawpanel.main.enabled='0'
uci set clawpanel.main.install_path=''
uci set clawpanel.main.openclaw_dir=''
uci set clawpanel.main.port='19527'
uci set clawpanel.main.edition='pro'
uci set clawpanel.main.version=''
uci commit clawpanel

exit 0
