include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-singbox-server
PKG_VERSION:=1.0.4
PKG_RELEASE:=0
PKG_MAINTAINER:=haixing1001

LUCI_TITLE:=LuCI support for sing-box server multi-instance
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-base +luci-compat

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
